#ifndef H_CONFIG_
#define H_CONFIG_

#define BATTERY_VOLTAGE_PIN 0
#define THERMAL_CAM_POWER_PIN 7
#define THERMAL_CAM_SDA_PIN 19
#define THERMAL_CAM_SCL_PIN 20
#define PAIR_BUTTON_PIN 9
#define USER_LED_PIN 15
// used as bt_name
#define DEVICE_NAME "thermalCam"
#define PAIR_BUTTON_TIMEOUT 10000
#define CAM_IDLE_TIMEOUT 10000
#define STATUS_NOTIFY_ITVL 10000 /* 10 seconds */
#define BLE_GAP_ADV_ITVL 1600    // 2s
#define LL_PACKET_TIME 2120
#define LL_PACKET_LENGTH 251
#define PREFERRED_MTU_VALUE 512
#define NUM_TEMPS_PIXELS 32 * 24
#define NUM_BYTES_PER_PIXEL 2
#define NUM_TEMPS_PACKETS 4
#define NUM_TEMPS_BYTES_TOTAL (NUM_TEMPS_PIXELS + NUM_TEMPS_PACKETS) * NUM_BYTES_PER_PIXEL // +NUM_TEMPS_PACKETS for the part number
#define NUM_TEMPS_BYTES_PER_PACKET NUM_TEMPS_BYTES_TOTAL / NUM_TEMPS_PACKETS
#define MAX_Q_ITEMS 4

#endif